name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20240522_14.1.1_x64-ucrt
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: fawazahmed0/action-debug@main
