name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20240203_13.2.1_x64-ucrt
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: mxschmitt/action-tmate@v3
