name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: |
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-pkg-config
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: fawazahmed0/action-debug@main
