name: ffmpeg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\m64-102
        key: m64-102
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL http://msystem.waw.pl/x265/mingw-gcc102-20200925.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'D:'
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Build
      continue-on-error: true
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: MINGW64
      run: |
        C:\msys64\usr\bin\bash -lc 'pacman -S yasm --noconfirm'
        curl -OL https://github.com/nyfair/MSYS2-packages/releases/download/dev/lame-dev-3.100-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/nyfair/MSYS2-packages/releases/download/dev/libogg-dev-1.3.4-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/nyfair/MSYS2-packages/releases/download/dev/libvorbis-aotuv-dev-1.3.7-1-x86_64.pkg.tar.zst
        curl -OL https://github.com/nyfair/MSYS2-packages/releases/download/dev/opus-dev-1.3.1-1-x86_64.pkg.tar.zst
        C:\msys64\usr\bin\bash -lc "pacman -U /d/a/MSYS2-packages/MSYS2-packages/*.zst --noconfirm"
        C:\msys64\usr\bin\bash -lc 'mv /mingw64 /64'
        C:\msys64\usr\bin\bash -lc 'cd /d/a/MSYS2-packages/MSYS2-packages/ffmpeg; PATH=/usr/bin:/opt/bin:/d/m64-102/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'
    - name: Verbose
      run: |
        C:\msys64\usr\bin\bash -lc "cd /d/a/MSYS2-packages/MSYS2-packages/ffmpeg; cat src/ffmpeg-4.3.1/ffbuild/config.log"
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ffmpeg/*pkg*.xz
        tag: latest
        overwrite: true
        file_glob: true
    - name: Upload Dev
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ffmpeg/*.zst
        tag: dev
        overwrite: true
        file_glob: true
