name: toolchain

on:
  workflow_dispatch:
  schedule:
  - cron: '25 0 * * 4'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\ucrt64
        key: mcf_20230905_13.2.1_x64-ucrt
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://gcc-mcf.lhmouse.com/mingw-w64-gcc-mcf_20230905_13.2.1_x64-ucrt_363e74bed272552d94a364cfa73fcda76dc7af9d.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'D:'
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Make Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        C:\msys64\usr\bin\bash -lc 'cd /d/a/mpv-win64/mpv-win64/mcfgthread; PATH=/usr/bin:/opt/bin:/d/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'
    - name: Delete
      if: steps.cache.outputs.cache-hit != 'true'
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: mcfgthread*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      if: steps.cache.outputs.cache-hit != 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mcfgthread/*pkg*.xz
        tag: latest
        overwrite: true
        file_glob: true
