name: vulkan-dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\m64-111
        key: m64-111
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL http://msystem.waw.pl/x265/mingw-gcc111-20210427.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'D:'
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: MINGW64
        CMAKE: /64/bin/cmake
      run: |
        C:\msys64\usr\bin\bash -lc 'mv /mingw64 /64'
        C:\msys64\usr\bin\bash -lc 'cd /d/a/mpv-win64/mpv-win64/vulkan-dev; PATH=/usr/bin:/opt/bin:/d/m64-111/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vulkan-dev/*.zst
        tag: dev
        overwrite: true
        file_glob: true